/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "adaptive_constants.h"



const adaptiveConstants g_adaptive_constants;

adaptiveConstants::adaptiveConstants() {
}



