export SHARDS_PER_SERVER="1"
export DATA_PATH="$SUCCINCT_HOME/dat"

export COORDINATOR_HOSTNAME="localhost"

export COORDINATOR_LOG_LEVEL="1" # Debug
export SERVER_LOG_LEVEL="1" # Debug

export COORDINATOR_PORT="11001"
export SERVER_PORT="11003"

## Core parameters
# export ISA_SAMPLING_RATE="32"
# export SA_SAMPLING_RATE="32"
# export NPA_SAMPLING_RATE="128"
# export SA_SAMPLING_SCHEME="0"
# export ISA_SAMPLING_SCHEME="0"
# export NPA_SAMPLING_SCHEME="1"
