/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef adaptive_CONSTANTS_H
#define adaptive_CONSTANTS_H

#include "thrift/adaptive_types.h"



class adaptiveConstants {
 public:
  adaptiveConstants();

};

extern const adaptiveConstants g_adaptive_constants;



#endif
