/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "coordinator_constants.h"

namespace succinct {

const coordinatorConstants g_coordinator_constants;

coordinatorConstants::coordinatorConstants() {
}

} // namespace

